### Business Optimsation

How to increase sales?

Objective:
Identify product, outlet and pricing characteristics associated with higher sales, which can support strategies for increasing revenue.

Since We git to know from the previous analysis that 'OUT027' has the highest average sales.

So why does this outlet perform so well?

## Data Reading

In [1]:
import pandas as pd

df=pd.read_parquet('c:\\Users\\Utkarsh\\Desktop\\Azure DataBricks Project\\Sales-Analytics-Using-Azure-Databricks\\data\\processed\\sales_cleaned.parquet')

In [2]:
import duckdb

duckdb.sql("Select * from df limit 5").df()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,MRP_Category
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Premium
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Low
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Medium
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Unknown,Tier 3,Grocery Store,732.3800,High
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Low

In [4]:
duckdb.sql("""Select 
           
    Outlet_Identifier,
    Outlet_Type,
    Outlet_Size,
    Outlet_Location_Type,
    Outlet_Establishment_Year,
    SUM(Item_Outlet_Sales) AS Total_Sales,
    AVG(Item_Outlet_Sales) AS Average_Sales

    from df
        
    Group by Outlet_Identifier,
        Outlet_Type,
        Outlet_Size,
        Outlet_Location_Type,
        Outlet_Establishment_Year

order by Average_Sales desc;
    
            """).df()

,Outlet_Identifier,Outlet_Type,Outlet_Size,Outlet_Location_Type,Outlet_Establishment_Year,Total_Sales,Average_Sales
0,OUT027,Supermarket Type3,Medium,Tier 3,1985,3.444468e+06,3695.781505
1,OUT035,Supermarket Type1,Small,Tier 2,2004,2.268123e+06,2438.841866
2,OUT049,Supermarket Type1,Medium,Tier 1,1999,2.183970e+06,2348.354635
3,OUT017,Supermarket Type1,Unknown,Tier 2,2007,2.167465e+06,2340.675263
4,OUT013,Supermarket Type1,High,Tier 3,1987,2.142664e+06,2298.995256
5,OUT046,Supermarket Type1,Small,Tier 1,1997,2.118395e+06,2277.844267
6,OUT045,Supermarket Type1,Unknown,Tier 2,2002,2.036725e+06,2192.384798
7,OUT018,Supermarket Type2,Medium,Tier 3,2009,1.851823e+06,1995.498739
8,OUT019,Grocery Store,Small,Tier 1,1985,1.795736e+05,340.746838
9,OUT010,Grocery Store,Unknown,Tier 3,1998,1.883402e+05,339.351662

Observation:

Supermarket outlets are associated with substantially higher average sales than Grocery Stores.

Supermarket Type3 is the highest-performing outlet type.

High-performing outlets are not restricted to a single location tier.

Within each outlet, which Item Types contribute the most total sales?

In [5]:
duckdb.sql("""Select 
           
            Outlet_Identifier,
            Item_Type,
            count (*) as Records,
            sum (Item_Outlet_Sales) as Total_Sales,
            avg(Item_Outlet_Sales) as Average_Sales


    from df
        
    Group by Outlet_Identifier,
        Item_Type,
        

order by Outlet_Identifier,
Total_Sales desc;
    
            """).df()

,Outlet_Identifier,Item_Type,Records,Total_Sales,Average_Sales
0,OUT010,Snack Foods,71,25942.8970,365.392915
1,OUT010,Household,67,25550.0750,381.344403
2,OUT010,Fruits and Vegetables,79,24548.0460,310.734759
3,OUT010,Frozen Foods,54,17942.6442,332.271189
4,OUT010,Dairy,43,15307.4078,355.986228
...,...,...,...,...,...
155,OUT049,Breads,25,60490.5932,2419.623728
156,OUT049,Others,17,47772.4816,2810.145976
157,OUT049,Starchy Foods,17,42019.9696,2471.762918
158,OUT049,Breakfast,13,30214.6698,2324.205369
159,OUT049,Seafood,7,11827.2712,1689.610171

OUT010's relatively high total sales within individual product categories are partly explained by having many records, while its low average sales indicate weaker sales performance per product-outlet observation.

In [7]:
duckdb.sql("""Select 
           
            Outlet_Identifier,
            Item_Type,
            count (*) as Records,
            sum (Item_Outlet_Sales) as Total_Sales,
            avg(Item_Outlet_Sales) as Average_Sales


    from df
    where Outlet_Identifier in ('OUT027','OUT010','OUT019')
    Group by Outlet_Identifier,
        Item_Type,
        

order by Outlet_Identifier,
Total_Sales desc;
    
            """).df()

,Outlet_Identifier,Item_Type,Records,Total_Sales,Average_Sales
0,OUT010,Snack Foods,71,25942.8970,365.392915
1,OUT010,Household,67,25550.0750,381.344403
2,OUT010,Fruits and Vegetables,79,24548.0460,310.734759
3,OUT010,Frozen Foods,54,17942.6442,332.271189
4,OUT010,Dairy,43,15307.4078,355.986228
5,OUT010,Meat,34,13580.9884,399.440835
6,OUT010,Health and Hygiene,37,13570.3356,366.765827
7,OUT010,Baking Goods,42,10693.4138,254.605090
8,OUT010,Soft Drinks,28,9441.0440,337.180143
9,OUT010,Canned,35,9019.5926,257.702646
10,OUT010,Breads,17,7657.3658,450.433282
11,OUT010,Breakfast,9,4081.3540,453.483778
12,OUT010,Hard Drinks,16,4067.3722,254.210762
13,OUT010,Others,10,3256.4278,325.642780
14,OUT010,Starchy Foods,9,2733.7748,303.752756
15,OUT010,Seafood,4,947.4334,236.858350
16,OUT019,Snack Foods,75,25653.2740,342.043653
17,OUT019,Fruits and Vegetables,73,24054.0224,329.507156
18,OUT019,Household,52,18157.0318,349.173688
19,OUT019,Canned,38,16739.5436,440.514305
20,OUT019,Dairy,49,16144.3184,329.475886
21,OUT019,Frozen Foods,49,15252.8122,311.281882
22,OUT019,Baking Goods,42,14013.0926,333.645062
23,OUT019,Meat,32,11995.7186,374.866206
24,OUT019,Health and Hygiene,30,10945.0862,364.836207
25,OUT019,Soft Drinks,26,9113.4704,350.518092
26,OUT019,Breads,16,4947.5598,309.222487
27,OUT019,Others,17,4522.1136,266.006682
28,OUT019,Breakfast,10,3762.4358,376.243580
29,OUT019,Hard Drinks,8,1768.3648,221.045600
30,OUT019,Seafood,6,1336.9264,222.821067
31,OUT019,Starchy Foods,4,1167.8132,291.953300
32,OUT027,Fruits and Vegetables,140,576028.1886,4114.487061
33,OUT027,Snack Foods,136,508653.8892,3740.102126
34,OUT027,Household,99,378299.5704,3821.207782
35,OUT027,Frozen Foods,88,314702.3544,3576.163118
36,OUT027,Canned,72,272150.4106,3779.866814
37,OUT027,Dairy,66,258863.7058,3922.177361
38,OUT027,Baking Goods,69,224172.1968,3248.872417
39,OUT027,Meat,56,216288.4590,3862.293911
40,OUT027,Health and Hygiene,60,199084.1870,3318.069783
41,OUT027,Soft Drinks,45,147822.2476,3284.938836
42,OUT027,Breads,31,110518.8052,3565.122748
43,OUT027,Hard Drinks,23,78957.8878,3432.951643
44,OUT027,Breakfast,11,50432.3526,4584.759327
45,OUT027,Starchy Foods,14,49170.6616,3512.190114
46,OUT027,Others,15,40513.9300,2700.928667
47,OUT027,Seafood,7,18809.5158,2687.073686

Observation:

OUT027 sales are substantially higher across almost all Item Types compared with the two low performing outlets.

OUT027, the only Supermarket Type3 outlet that has the highest average sales.

So the question was "how can the business increase sales?"

Finding 1:
OUT027 is the highest performing outlet

Finding 2:
Its performance isn't restricted to one Item Type

Finding 3:
The same Item type in other outlets having huge difference in average sales agaianst OUT027.

,Item_Identifier,Outlet_Identifier,Item_Type,Item_MRP,Item_Outlet_Sales
0,NCK30,OUT010,Household,254.2698,1775.6886
1,FDJ55,OUT010,Meat,224.8404,1575.2828
2,FDV59,OUT010,Breads,219.2166,1524.0162
3,NCX41,OUT010,Health and Hygiene,211.0244,1482.0708
4,FDM08,OUT010,Fruits and Vegetables,225.5088,1342.2528
...,...,...,...,...,...
8509,FDL48,OUT049,Baking Goods,48.5034,243.0170
8510,FDR08,OUT049,Fruits and Vegetables,111.0886,222.3772
8511,FDJ45,OUT049,Seafood,34.8216,207.7296
8512,DRK49,OUT049,Soft Drinks,41.5138,162.4552
8513,FDF09,OUT049,Fruits and Vegetables,37.4848,111.8544